# Generated by Django 4.2.13 on 2024-06-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan_approve',
        ),
    ]
